# Generated by Django 2.2.8 on 2020-02-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_brith',
            new_name='date_of_birth',
        ),
    ]
